# Web Scraping of "Welcome to the Jungle" for Data Jobs in Paris

### Importing librairies and modules

In [1]:
import requests
import pandas as pd

### Welcome to the Jungle website

Let's effectuate a research filtering with the criterias needed for my seach:
- Your dream job? --> Data Analyst
- Where? --> Paris

Therefore, here's the URL I will need to scrap:

In [2]:
URL = "https://csekhvms53-3.algolianet.com/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.24.12%3Breact-instantsearch%205.3.2%3BJS%20Helper%20(2.28.1)&x-algolia-application-id=CSEKHVMS53&x-algolia-api-key=02f0d440abc99cae37e126886438b266"

In [3]:
text = """accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 2049
content-type: application/x-www-form-urlencoded
Host: csekhvms53-3.algolianet.com
Origin: https://www.welcometothejungle.com
Pragma: no-cache
Referer: https://www.welcometothejungle.com/en/jobs?query=data%20analyst&page=1&aroundQuery=Paris%2C%20France&aroundLatLng=48.85718%2C2.34141&aroundRadius=20000&sortBy=mostRecent
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"""

In [4]:
headers = {h[0]:h[1] for x in text.split('\n') if (h := x.split(': '))}
headers

{'accept': 'application/json',
 'Accept-Encoding': 'gzip, deflate, br',
 'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8',
 'Cache-Control': 'no-cache',
 'Connection': 'keep-alive',
 'Content-Length': '2049',
 'content-type': 'application/x-www-form-urlencoded',
 'Host': 'csekhvms53-3.algolianet.com',
 'Origin': 'https://www.welcometothejungle.com',
 'Pragma': 'no-cache',
 'Referer': 'https://www.welcometothejungle.com/en/jobs?query=data%20analyst&page=1&aroundQuery=Paris%2C%20France&aroundLatLng=48.85718%2C2.34141&aroundRadius=20000&sortBy=mostRecent',
 'Sec-Fetch-Dest': 'empty',
 'Sec-Fetch-Mode': 'cors',
 'Sec-Fetch-Site': 'cross-site',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'}

In [24]:
# Since it is a POST request, I will need a "data" argument that I will call payload. The website call it "Form Data"
df = pd.DataFrame()
for i in range(8):
    payload = """{"requests":[{"indexName":"wk_cms_jobs_production_published_at_desc","params":"query=data%20analyst&hitsPerPage=30&maxValuesPerFacet=100&page="""+str(i)+"""&restrictSearchableAttributes=%5B%22name%22%2C%22profile%22%2C%22organization.name%22%2C%22office.city%22%2C%22office.district%22%2C%22office.state%22%2C%22office.country%22%2C%22department%22%2C%22profession.name.en%22%2C%22profession.category.en%22%2C%22contract_type_names.en%22%2C%22sectors.name.en%22%2C%22sectors.parent.en%22%5D&highlightPreTag=%3Cais-highlight-0000000000%3E&highlightPostTag=%3C%2Fais-highlight-0000000000%3E&aroundLatLng=48.85718%2C2.34141&aroundRadius=20000&aroundPrecision=20000&disableTypoToleranceOnAttributes=%5B%22profile%22%5D&filters=website.reference%3Awttj_fr&facets=%5B%22office.country_code%22%2C%22office.state%22%2C%22office.district%22%2C%22office.location%22%2C%22online%22%2C%22remote%22%2C%22contract_type_names.en%22%2C%22sectors.parent.en%22%2C%22profession.category.en%22%2C%22experience_level_minimum%22%2C%22organization.size.en%22%2C%22language%22%5D&tagFilters=&numericFilters=%5B%22experience_level_minimum%3E%3D0%22%2C%22experience_level_minimum%3C%3D15%22%5D"},{"indexName":"wk_cms_jobs_production_published_at_desc","params":"query=data%20analyst&hitsPerPage=1&maxValuesPerFacet=100&page=0&restrictSearchableAttributes=%5B%22name%22%2C%22profile%22%2C%22organization.name%22%2C%22office.city%22%2C%22office.district%22%2C%22office.state%22%2C%22office.country%22%2C%22department%22%2C%22profession.name.en%22%2C%22profession.category.en%22%2C%22contract_type_names.en%22%2C%22sectors.name.en%22%2C%22sectors.parent.en%22%5D&highlightPreTag=%3Cais-highlight-0000000000%3E&highlightPostTag=%3C%2Fais-highlight-0000000000%3E&aroundLatLng=48.85718%2C2.34141&aroundRadius=20000&aroundPrecision=20000&disableTypoToleranceOnAttributes=%5B%22profile%22%5D&filters=website.reference%3Awttj_fr&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&analytics=false&clickAnalytics=false&facets=experience_level_minimum"}]}"""
    response = requests.post(URL, headers=headers, data=payload)
    data = response.json()["results"][0]["hits"]
    df = pd.concat([df, pd.json_normalize(data)])
df

,slug,name,profile,language,published_at,reference,sectors,contract_type,experience_level_minimum,department,...,profession_name.fr.Relation client,profession_name.en.Customer Service,profession_name.es.Relaci√≥n con los clientes,profession_name.cs.Z√°kaznick√Ω servis,profession_name.sk.Z√°kazn√≠cky servis,profession_name.fr.Cr√©a,profession_name.en.Design,profession_name.es.Dise√±o y creatividad,profession_name.cs.Design,profession_name.sk.Dizajn
0,revenue-strategy-and-business-analyst-h-f_paris,Data analyst - revenue strategy H/F,* Tu justifies d‚Äôau moins une premi√®re exp√©rie...,fr,2021-02-18T17:10:25.770+01:00,WEDOO_rxbK3b9,"[{'name': {'fr': 'Application mobile', 'en': '...",FULL_TIME,0.5,Enseignes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,analyste-conformite_paris_MOONC_WaOlWMA,Analyste Conformit√©,Bac +3/+5 en Banque/ Conformit√©\r\nVous avez d...,fr,2021-02-18T16:55:59.821+01:00,MOONC_WaOlWMA,"[{'name': {'fr': 'Banque', 'en': 'Banking', 'e...",FULL_TIME,2.0,Customer Service,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,senior-data-strategist_paris,Senior Data Strategist H/F CDI,Dipl√¥m√© d‚Äôune √©cole d‚Äôing√©nieur ou de commerce...,fr,2021-02-18T15:42:48.120+01:00,FABER_973JKVD,"[{'name': {'fr': 'IT / Digital', 'en': 'IT / D...",FULL_TIME,3.0,Marketing Digital,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,senior-data-product-manager-h-f-cdi_paris,Senior Data Product Manager (H/F) - CDI - üá´üá∑,* Issu(e) d‚Äôune grande √©cole d‚Äôing√©nieur ou de...,fr,2021-02-18T15:02:01.142+01:00,PAPER_KPZgMa0,"[{'name': {'fr': 'Logiciels', 'en': 'Software'...",FULL_TIME,2.0,Marketing & Growth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,head-of-data-analytics_paris,Head of Data analytics,**Who are you?**\r\n\r\n*Must-have*\r\n\r\n* 8...,en,2021-02-18T14:32:21.564+01:00,LUKO_bV70ZAm,[{'name': {'fr': 'Intelligence artificielle / ...,FULL_TIME,7.0,AI & Tech,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,business-operations-data-analyst-h-f_clichy,Business Operations Data Analyst (H/F),Profil\r\n\r\nVos comp√©tences :\r\n‚Ä¢\tComp√©ten...,fr,2021-01-13T18:28:20.780+01:00,OPENI_1zRZkJM,"[{'name': {'fr': 'IT / Digital', 'en': 'IT / D...",FULL_TIME,2.0,Direction G√©n√©rale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,operations-analyst-h-f_paris,Operations Analyst (H/F),**About you**\r\n\r\n* You are fluent and have...,en,2021-01-13T11:01:21.271+01:00,OWKIN_5GamajX,[{'name': {'fr': 'Intelligence artificielle / ...,FULL_TIME,1.0,Operations,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,traffic-manager-pre-embauche_paris,Acquisition Manager (Pr√©-embauche),- Analytique/ Data-driven : Vous aimez manipul...,fr,2021-01-12T18:08:16.849+01:00,IA_GAwe50z,[{'name': {'fr': 'Digital Marketing / Data Mar...,INTERNSHIP,1.0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,manager-audience-et-performance-h-f_boulogne-b...,Responsable Data Analyst Solutions B2B (H/F),Formation sup√©rieure niveau Bac +5 dans les st...,fr,2021-01-12T13:56:59.140+01:00,SOLOC_z5e0ZR3,"[{'name': {'fr': 'IT / Digital', 'en': 'IT / D...",FULL_TIME,5.0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,data-analyst-h-f_paris,Data Analyst (H/F),Votre exp√©rience et vos qualit√©s :\r\n* Au moi...,fr,2021-01-12T12:20:21.843+01:00,JOONE_J3b4KJ8,"[{'name': {'fr': 'E-commerce', 'en': 'E-commer...",FULL_TIME,2.0,EXPANSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df = df.reset_index()

In [30]:
df.drop(columns="index", axis=1, inplace=True)
df

KeyError: "['index'] not found in axis"

## Understanding the data

In [31]:
df.shape

(240, 193)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Columns: 193 entries, slug to profession_name.sk.Dizajn
dtypes: float64(3), object(190)
memory usage: 362.0+ KB

In [34]:
df.iloc[:,10:30]

,remote,objectID,website.reference,organization.name,organization.slug,organization.reference,organization.size.fr,organization.size.en,organization.size.es,organization.size.cs,organization.size.sk,organization.logo.url,organization.logo.thumb.url,organization.labels,organization.cover_image.fr.url,organization.cover_image.fr.large.url,organization.cover_image.fr.thumb.url,organization.cover_image.fr.small.url,organization.cover_image.en.url,organization.cover_image.en.large.url
0,no,476838,wttj_fr,Wedoogift,wedoogift,pk8Ze3K,Entre 50 et 250 salari√©s,Between 50 and 250 employees,Entre 50 y 250 empleados,Od 50 do 250 zamƒõstnanc≈Ø,Od 50 do 250 zamestnancov,https://cdn-images.welcometothejungle.com/L45Y...,https://cdn-images.welcometothejungle.com/OzE5...,[],https://cdn-images.welcometothejungle.com/1Cl1...,https://cdn-images.welcometothejungle.com/UMzs...,https://cdn-images.welcometothejungle.com/fhyz...,https://cdn-images.welcometothejungle.com/ek2g...,https://cdn-images.welcometothejungle.com/1Cl1...,https://cdn-images.welcometothejungle.com/UMzs...
1,no,493447,wttj_fr,Mooncard,mooncard,rYxo7wR,Entre 15 et 50 salari√©s,Between 15 and 50 employees,Entre 15 y 50 empleados,Od 15 do 50 zamƒõstnanc≈Ø,Od 15 do 50 zamestnancov,https://cdn-images.welcometothejungle.com/asm3...,https://cdn-images.welcometothejungle.com/LcAQ...,[],https://cdn-images.welcometothejungle.com/jFyZ...,https://cdn-images.welcometothejungle.com/iFpL...,https://cdn-images.welcometothejungle.com/TOQn...,https://cdn-images.welcometothejungle.com/CpvJ...,https://cdn-images.welcometothejungle.com/jFyZ...,https://cdn-images.welcometothejungle.com/iFpL...
2,punctual,491884,wttj_fr,FABERNOVEL,fabernovel,lMW728Z,Entre 250 et 2000 salari√©s,"Between 250 and 2,000 employees",Entre 250 y 2000 empleados,Od 250 do 2 000 zamƒõstnanc≈Ø,Od 250 do 2 000 zamestnancov,https://cdn-images.welcometothejungle.com/m0Kh...,https://cdn-images.welcometothejungle.com/vD1c...,[],https://cdn-images.welcometothejungle.com/ujwk...,https://cdn-images.welcometothejungle.com/syX1...,https://cdn-images.welcometothejungle.com/NTeM...,https://cdn-images.welcometothejungle.com/LYKC...,https://cdn-images.welcometothejungle.com/epXQ...,https://cdn-images.welcometothejungle.com/tJmJ...
3,partial,493329,wttj_fr,papernest,souscritoo,3jRk35,Entre 250 et 2000 salari√©s,"Between 250 and 2,000 employees",Entre 250 y 2000 empleados,Od 250 do 2 000 zamƒõstnanc≈Ø,Od 250 do 2 000 zamestnancov,https://cdn-images.welcometothejungle.com/-0Pn...,https://cdn-images.welcometothejungle.com/YNpZ...,[],https://cdn-images.welcometothejungle.com/2oYK...,https://cdn-images.welcometothejungle.com/HdhL...,https://cdn-images.welcometothejungle.com/2ecN...,https://cdn-images.welcometothejungle.com/XqcC...,https://cdn-images.welcometothejungle.com/WTCm...,https://cdn-images.welcometothejungle.com/Q9OD...
4,fulltime,462020,wttj_fr,Luko,la-societe-demain-es-sas,QaZy5Kz,Entre 50 et 250 salari√©s,Between 50 and 250 employees,Entre 50 y 250 empleados,Od 50 do 250 zamƒõstnanc≈Ø,Od 50 do 250 zamestnancov,https://cdn-images.welcometothejungle.com/lN3z...,https://cdn-images.welcometothejungle.com/VCOb...,[],https://cdn-images.welcometothejungle.com/TY_0...,https://cdn-images.welcometothejungle.com/5VaO...,https://cdn-images.welcometothejungle.com/nbqR...,https://cdn-images.welcometothejungle.com/J5YA...,https://cdn-images.welcometothejungle.com/TY_0...,https://cdn-images.welcometothejungle.com/5VaO...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,partial,423932,wttj_fr,OpenIP,openip,Jwb2Rp4,Entre 50 et 250 salari√©s,Between 50 and 250 employees,Entre 50 y 250 empleados,Od 50 do 250 zamƒõstnanc≈Ø,Od 50 do 250 zamestnancov,https://cdn-images.welcometothejungle.com/gE3p...,https://cdn-images.welcometothejungle.com/4q8o...,NaN,https://cdn-images.welcometothejungle.com/fjbY...,https://cdn-images.welcometothejungle.com/l1ea...,https://cdn-images.welcometothejungle.com/p6-O...,https://cdn-images.welcometothejungle.com/6fEV...,https://cdn-images.welcometothejungle.com/fjbY...,https://cdn-images.welcometothejungle.com/l1ea...
236,partial,462834,wttj_fr,Owkin,owkin,JoKemDV,Entre 50 et 250 salari√©s,Between 50 and 250 employees,Entre 50 y 250 empleados,Od 50 do 250 zamƒõstnanc≈Ø,Od 50 do 250 zamestnancov,https://cdn-images.welcometothejungle.com/T7kR...,https://cdn-images.welcometothejungle.com/_in_...,NaN,https://cdn-images.welcometothejungle.com/j8FW...,https://cdn-images.welcometothejungle.com/LELF...,https://cdn-images.welcometothejungle.com/UvSt...,https://cdn-images.welcometothejungle.com/A0J7...,https://cdn-images.welcometothejungle.com/atyt...,https://cdn-images.welcometothejungle.com/s88z...
237,partial,462485,wttj_fr,Impulse Analytics,impulse-analytics,xy06y4m,< 15 salari√©s,< 15 employees,< 15 empleados,< 15 zamƒõstnanc≈Ø,< 15 zamestnancov,https://cdn-images.welcometothejungle.com/592n...,https://cdn-images.welcometothejungle.com/JQXv...,[],https://cdn-images.welcometothejungle.com/J4NL...,https://cdn-images.welcometothejungle.com/raGh...,https://cdn-images.welcometothejungle.com/xRFr...,https://cdn-images.welcometothejungle.com/rYZj...,https://cdn-images.welcometothejungle.com/J4NL...,https://cdn-images.welcometothejungle.com/raGh...
238,punctual,462215,wttj_fr,Solocal,solocal,PYLWlqk,> 2000 salari√©s,"> 2,000 employees",> 2000 empleados,> 2 000 zamƒõstnanc≈Ø,> 2 000 zamestnancov,https://cdn-images.welcometothejungle.com/J2Iu...,https://cdn-images.welcometothejungle.com/ZGwY...,NaN,https://cdn-images.welcometothejungle.com/Lf4y...,https://cdn-images.welcometothejungle.com/3ofl...,https://cdn-images.welcometothejungle.com/9QhH...,https://cdn-images.welcometothejungle.com/V6wu...,https://cdn-images.welcometothejungle.com/Lf4y...,https://cdn-images.welcometothejungle.com/3ofl...
239,no,462174,wttj_fr,Joone,joone,Jywlm5V,Entre 50 et 250 salari√©s,Between 50 and 250 employees,Entre 50 y 250 empleados,Od 50 do 250 zamƒõstnanc≈Ø,Od 50 do 250 zamestnancov,https://cdn-images.welcometothejungle.com/BdVn...,https://cdn-images.welcometothejungle.com/u3CS...,NaN,https://cdn-images.welcometothejungle.com/juJ8...,https://cdn-images.welcometothejungle.com/NXrl...,https://cdn-images.welcometothejungle.com/4-kd...,https://cdn-images.welcometothejungle.com/oboP...,https://cdn-images.welcometothejungle.com/juJ8...,https://cdn-images.welcometothejungle.com/NXrl...

In [35]:
df.describe(include="all")

,slug,name,profile,language,published_at,reference,sectors,contract_type,experience_level_minimum,department,...,profession_name.fr.Relation client,profession_name.en.Customer Service,profession_name.es.Relaci√≥n con los clientes,profession_name.cs.Z√°kaznick√Ω servis,profession_name.sk.Z√°kazn√≠cky servis,profession_name.fr.Cr√©a,profession_name.en.Design,profession_name.es.Dise√±o y creatividad,profession_name.cs.Design,profession_name.sk.Dizajn
count,240,240,225,240,240,240,240,240,240.000000,127,...,2,2,2,2,2,1,1,1,1,1
unique,226,215,216,2,240,240,132,5,NaN,73,...,1,1,1,1,1,1,1,1,1,1
top,data-analyst_paris,Data Analyst,,fr,2021-02-18T09:00:04.499+01:00,RF_3RkAGPm,"[{'name': {'fr': 'FinTech / InsurTech', 'en': ...",FULL_TIME,NaN,Data,...,Customer Success,Customer Success,√âxito del cliente,Customer Success,Customer Success,UI Design,UI Design,Dise√±o UI,UI Design,UI Design
freq,11,13,5,169,1,1,9,178,NaN,12,...,2,2,2,2,2,1,1,1,1,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.460417,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.761839,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.750000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Data Cleaning

In [36]:
# Dropping all rows and columns that are filled with NA results:
df.dropna(axis=0, how="all")
df.dropna(axis=1, how="all")
df.shape

(240, 193)

### Cleaning columns columns that show duplicated content in other languages other than English:

In [52]:
# Identifying all the columns :
col = []
for language in [".cs", ".es", ".fr", ".sk"]:
    col += [c for c in df.columns if language in c]
col

['organization.size.cs',
 'organization.cover_image.cs.url',
 'organization.cover_image.cs.large.url',
 'organization.cover_image.cs.thumb.url',
 'organization.cover_image.cs.small.url',
 'sectors_name.cs',
 'contract_type_names.cs',
 'profession.name.cs',
 'profession.category.cs',
 'profession_name.cs.Business',
 '_highlightResult.contract_type_names.cs.value',
 '_highlightResult.contract_type_names.cs.matchLevel',
 '_highlightResult.contract_type_names.cs.matchedWords',
 '_highlightResult.profession.name.cs.value',
 '_highlightResult.profession.name.cs.matchLevel',
 '_highlightResult.profession.name.cs.matchedWords',
 '_highlightResult.profession.category.cs.value',
 '_highlightResult.profession.category.cs.matchLevel',
 '_highlightResult.profession.category.cs.matchedWords',
 'profession_name.cs.Audit / Finance / Poji≈°≈•ovnictv√≠',
 'profession_name.cs.Tech',
 '_highlightResult.profession.name.cs.fullyHighlighted',
 'profession_name.cs.Marketing a komunikace',
 'profession_name.cs.Podpora',
 'profession_name.cs.Consulting',
 'profession_name.cs.Z√°kaznick√Ω servis',
 'profession_name.cs.Design',
 'organization.size.es',
 'organization.cover_image.es.url',
 'organization.cover_image.es.large.url',
 'organization.cover_image.es.thumb.url',
 'organization.cover_image.es.small.url',
 'sectors_name.es',
 'contract_type_names.es',
 'profession.name.es',
 'profession.category.es',
 'profession_name.es.Negocios',
 '_highlightResult.contract_type_names.es.value',
 '_highlightResult.contract_type_names.es.matchLevel',
 '_highlightResult.contract_type_names.es.matchedWords',
 '_highlightResult.profession.name.es.value',
 '_highlightResult.profession.name.es.matchLevel',
 '_highlightResult.profession.name.es.matchedWords',
 '_highlightResult.profession.category.es.value',
 '_highlightResult.profession.category.es.matchLevel',
 '_highlightResult.profession.category.es.matchedWords',
 'profession_name.es.Auditor√≠a/Finanzas/Seguros',
 'profession_name.es.Tecnolog√≠a',
 'profession_name.es.Marketing/Comunicaci√≥n',
 'profession_name.es.Servicios generales',
 'profession_name.es.Asesor√≠a',
 'profession_name.es.Relaci√≥n con los clientes',
 'profession_name.es.Dise√±o y creatividad',
 'organization.size.fr',
 'organization.cover_image.fr.url',
 'organization.cover_image.fr.large.url',
 'organization.cover_image.fr.thumb.url',
 'organization.cover_image.fr.small.url',
 'sectors_name.fr',
 'contract_type_names.fr',
 'profession.name.fr',
 'profession.category.fr',
 'profession_name.fr.Business',
 '_highlightResult.contract_type_names.fr.value',
 '_highlightResult.contract_type_names.fr.matchLevel',
 '_highlightResult.contract_type_names.fr.matchedWords',
 '_highlightResult.profession.name.fr.value',
 '_highlightResult.profession.name.fr.matchLevel',
 '_highlightResult.profession.name.fr.matchedWords',
 '_highlightResult.profession.category.fr.value',
 '_highlightResult.profession.category.fr.matchLevel',
 '_highlightResult.profession.category.fr.matchedWords',
 'profession_name.fr.Audit / Finance / Assurance',
 'profession_name.fr.Tech',
 '_highlightResult.profession.name.fr.fullyHighlighted',
 'profession_name.fr.Marketing / Communication',
 'profession_name.fr.Support',
 'profession_name.fr.Conseil',
 'profession_name.fr.Relation client',
 'profession_name.fr.Cr√©a',
 'organization.size.sk',
 'organization.cover_image.sk.url',
 'organization.cover_image.sk.large.url',
 'organization.cover_image.sk.thumb.url',
 'organization.cover_image.sk.small.url',
 'sectors_name.sk',
 'contract_type_names.sk',
 'profession.name.sk',
 'profession.category.sk',
 'profession_name.sk.Obchod',
 '_highlightResult.contract_type_names.sk.value',
 '_highlightResult.contract_type_names.sk.matchLevel',
 '_highlightResult.contract_type_names.sk.matchedWords',
 '_highlightResult.profession.name.sk.value',
 '_highlightResult.profession.name.sk.matchLevel',
 '_highlightResult.profession.name.sk.matchedWords',
 '_highlightResult.profession.category.sk.value',
 '_highlightResult.profession.category.sk.matchLevel',
 '_highlightResult.profession.category.sk.matchedWords',
 'profession_name.sk.Audit / Financie / Pois≈•ovn√≠ctvo',
 'profession_name.sk.Technol√≥gie',
 '_highlightResult.profession.name.sk.fullyHighlighted',
 'profession_name.sk.Marketing / Komunik√°cia',
 'profession_name.sk.Podpora',
 'profession_name.sk.Poradenstvo',
 'profession_name.sk.Z√°kazn√≠cky servis',
 'profession_name.sk.Dizajn']

In [53]:
len(col)

107

In [55]:
df.drop(axis=1, columns=col, inplace=True)
df.shape

(240, 86)

In [56]:
# Printing the new columns of our DataFrame
col = [c for c in df.columns]
col

['slug',
 'name',
 'profile',
 'language',
 'published_at',
 'reference',
 'sectors',
 'contract_type',
 'experience_level_minimum',
 'department',
 'remote',
 'objectID',
 'website.reference',
 'organization.name',
 'organization.slug',
 'organization.reference',
 'organization.size.en',
 'organization.logo.url',
 'organization.logo.thumb.url',
 'organization.labels',
 'organization.cover_image.en.url',
 'organization.cover_image.en.large.url',
 'organization.cover_image.en.thumb.url',
 'organization.cover_image.en.small.url',
 'organization.website_organization.slug',
 'sectors_name.en',
 'contract_type_names.en',
 'office.city',
 'office.district',
 'office.state',
 'office.country',
 'office.country_code',
 'profession.name.en',
 'profession.category.en',
 'profession_name.en.Business',
 '_geoloc.lat',
 '_geoloc.lng',
 '_highlightResult.name.value',
 '_highlightResult.name.matchLevel',
 '_highlightResult.name.fullyHighlighted',
 '_highlightResult.name.matchedWords',
 '_highlightResult.profile.value',
 '_highlightResult.profile.matchLevel',
 '_highlightResult.profile.fullyHighlighted',
 '_highlightResult.profile.matchedWords',
 '_highlightResult.organization.name.value',
 '_highlightResult.organization.name.matchLevel',
 '_highlightResult.organization.name.matchedWords',
 '_highlightResult.sectors',
 '_highlightResult.contract_type_names.en.value',
 '_highlightResult.contract_type_names.en.matchLevel',
 '_highlightResult.contract_type_names.en.matchedWords',
 '_highlightResult.office.city.value',
 '_highlightResult.office.city.matchLevel',
 '_highlightResult.office.city.matchedWords',
 '_highlightResult.office.district.value',
 '_highlightResult.office.district.matchLevel',
 '_highlightResult.office.district.matchedWords',
 '_highlightResult.office.state.value',
 '_highlightResult.office.state.matchLevel',
 '_highlightResult.office.state.matchedWords',
 '_highlightResult.office.country.value',
 '_highlightResult.office.country.matchLevel',
 '_highlightResult.office.country.matchedWords',
 '_highlightResult.office.country_code.value',
 '_highlightResult.office.country_code.matchLevel',
 '_highlightResult.office.country_code.matchedWords',
 '_highlightResult.department.value',
 '_highlightResult.department.matchLevel',
 '_highlightResult.department.matchedWords',
 '_highlightResult.profession.name.en.value',
 '_highlightResult.profession.name.en.matchLevel',
 '_highlightResult.profession.name.en.matchedWords',
 '_highlightResult.profession.category.en.value',
 '_highlightResult.profession.category.en.matchLevel',
 '_highlightResult.profession.category.en.matchedWords',
 'profession_name.en.Audit / Finance / Insurance',
 'profession_name.en.Tech',
 '_highlightResult.profession.name.en.fullyHighlighted',
 'profession_name.en.Marketing / Communications',
 'profession_name.en.Support Roles',
 'profession_name.en.Consulting',
 '_highlightResult.department.fullyHighlighted',
 '_highlightResult.organization.name.fullyHighlighted',
 'profession_name.en.Customer Service',
 'profession_name.en.Design']

### Droping all the "Organization" columns that don't interest me:

In [58]:
df.iloc[:,10:20]

,remote,objectID,website.reference,organization.name,organization.slug,organization.reference,organization.size.en,organization.logo.url,organization.logo.thumb.url,organization.labels
0,no,476838,wttj_fr,Wedoogift,wedoogift,pk8Ze3K,Between 50 and 250 employees,https://cdn-images.welcometothejungle.com/L45Y...,https://cdn-images.welcometothejungle.com/OzE5...,[]
1,no,493447,wttj_fr,Mooncard,mooncard,rYxo7wR,Between 15 and 50 employees,https://cdn-images.welcometothejungle.com/asm3...,https://cdn-images.welcometothejungle.com/LcAQ...,[]
2,punctual,491884,wttj_fr,FABERNOVEL,fabernovel,lMW728Z,"Between 250 and 2,000 employees",https://cdn-images.welcometothejungle.com/m0Kh...,https://cdn-images.welcometothejungle.com/vD1c...,[]
3,partial,493329,wttj_fr,papernest,souscritoo,3jRk35,"Between 250 and 2,000 employees",https://cdn-images.welcometothejungle.com/-0Pn...,https://cdn-images.welcometothejungle.com/YNpZ...,[]
4,fulltime,462020,wttj_fr,Luko,la-societe-demain-es-sas,QaZy5Kz,Between 50 and 250 employees,https://cdn-images.welcometothejungle.com/lN3z...,https://cdn-images.welcometothejungle.com/VCOb...,[]
...,...,...,...,...,...,...,...,...,...,...
235,partial,423932,wttj_fr,OpenIP,openip,Jwb2Rp4,Between 50 and 250 employees,https://cdn-images.welcometothejungle.com/gE3p...,https://cdn-images.welcometothejungle.com/4q8o...,NaN
236,partial,462834,wttj_fr,Owkin,owkin,JoKemDV,Between 50 and 250 employees,https://cdn-images.welcometothejungle.com/T7kR...,https://cdn-images.welcometothejungle.com/_in_...,NaN
237,partial,462485,wttj_fr,Impulse Analytics,impulse-analytics,xy06y4m,< 15 employees,https://cdn-images.welcometothejungle.com/592n...,https://cdn-images.welcometothejungle.com/JQXv...,[]
238,punctual,462215,wttj_fr,Solocal,solocal,PYLWlqk,"> 2,000 employees",https://cdn-images.welcometothejungle.com/J2Iu...,https://cdn-images.welcometothejungle.com/ZGwY...,NaN
239,no,462174,wttj_fr,Joone,joone,Jywlm5V,Between 50 and 250 employees,https://cdn-images.welcometothejungle.com/BdVn...,https://cdn-images.welcometothejungle.com/u3CS...,NaN